chore: use dorshinar/get-deployment-url to get deployment url

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -5,19 +5,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Extract branch name
-        shell: bash
-        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF#refs/heads/} | sed 's/\//-/g')"
       - uses: actions/setup-node@v1
         with:
           node-version: 12
       - run: npm install -g @lhci/cli@0.3.x
-      - uses: ho-nl/wait-for-url-action@master
-        id: wait
-        with:
-          url: https://project-reachdigital-nl-git-${BRANCH_NAME}.reachdigital.now.sh
-          max_timeout: 600
-      - if: steps.wait.outputs.conclusion == 'success'
-        run: lhci autorun --collect.url=https://project-reachdigital-nl-git-${BRANCH_NAME}.reachdigital.now.sh || echo "failed with errors"
+      - name: Get deployment URL
+          id: deployment
+          uses: dorshinar/get-deployment-url@v1.0.0
+          timeout-minutes: 5
+          with:
+            token: ${{ secrets.GITHUB_TOKEN }}
+      - run: lhci autorun --collect.url=${{ steps.deployment.outputs.deployment }} || echo "failed with errors"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
